services:
  searxng:
    image: ghcr.io/searxng/searxng:latest
    restart: unless-stopped
    environment:
      SEARXNG_BASE_URL: ${SEARXNG_BASE_URL}
      SEARXNG_SECRET: ${SEARXNG_SECRET}
      SEARXNG_PUBLIC_INSTANCE: ${SEARXNG_PUBLIC_INSTANCE}
      SEARXNG_LIMITER: ${SEARXNG_LIMITER}
      SEARXNG_IMAGE_PROXY: ${SEARXNG_IMAGE_PROXY}
      SEARXNG_METHOD: ${SEARXNG_METHOD}
      SEARXNG_DEBUG: ${SEARXNG_DEBUG}
    volumes:
      - searxng-config:/etc/searxng
      - searxng-data:/var/cache/searxng
    ports:
      - "8080:8080"

volumes:
  searxng-config:
  searxng-data:
