use_default_settings: true

server:
  public_instance: false
  limiter: false

search:
  formats:
    - html
    - json

engines:
  - name: ahmia
    disabled: true
  - name: torch
    disabled: true
